### ISSUE TITLE
Symfony3 support

### ISSUE THREAD

**Issue by paul-mesnilgrente** [ornj/markdown-bundle#6]
Hello,
I tried to use it with Symfony 3 but the 'markdown' does not work anymore with symfony3, we should use `MarkdownType::class` instead.

Do you think to still work on it ?

Best regards.

**Comment by ornj** [comment]
I haven't been actively maintaining this since I haven't been using PHP/Symfony for a few years now. If you wanted to submit a PR to get this working in Symfony3 that would be great.

**Comment by paul-mesnilgrente** [comment]
Sorry I haven't got the time to work on this.
Best regards.
